---

- name: Ensure Hadoop directories exist
  file:
          state: directory
          path: "{{ item }}"
          mode: 0755
          owner: "{{ hadoop_user }}"
          group: "{{ hadoop_group }}"
  loop:
          - "{{ hadoop_download_dir }}"
          - "{{ hadoop_install_dir }}"
          - "{{ hadoop_logs_dir }}"
          - "{{ hadoop_conf_dir }}"
          - "{{ hdfs_home }}"
          - "{{ hdfs_namenode_dir }}"
          - "{{ hdfs_datanode_dir }}"
          - "{{ yarn_home }}"
          - "{{ yarn_logs_dir }}"

- name: Download Hadoop distribution
  become: yes
  get_url:
          url: "{{ hadoop_mirror }}/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
          dest: "{{ hadoop_download_dir }}/hadoop.tar.gz"
          timeout: 60
  tags: master

- name: Extract Hadoop distribution
  become: yes
  unarchive:
          src: "{{ hadoop_download_dir }}/hadoop.tar.gz"
          dest: "{{ hadoop_install_dir }}"
          owner: "{{ hadoop_user }}"
          group: "{{ hadoop_group }}"
          extra_opts: [--strip-components=1]
          keep_newer: yes
          remote_src: yes
  tags: master

- name: Copy Hadoop configuration files
  become: yes
  template:
          src: "{{ item }}"
          dest: "{{ hadoop_home }}/etc/hadoop/{{ item | basename | regex_replace('.j2','') }}"
          owner: "{{ hadoop_user }}"
          group: "{{ hadoop_group }}"
  with_fileglob:
          - ../templates/*.j2

- name: Create Hadoop systemd service files
  become: yes
  template:
          src: "{{ item }}"
          dest: "/etc/systemd/system/{{ item | basename | regex_replace('.j2','') }}"
          owner: root
          group: root
  with_fileglob:
          - ../templates/systemd/*.j2 

- name: Ensure netdata extra HDFS directories exist
  file:
          state: directory
          path: "/etc/netdata/{{ item }}/"
          owner: root
          group: root
  loop:
          - go.d
          - health.d

- name: Create netdata hdfs.conf file
  template: src=netdata/hdfs.conf.j2 dest=/etc/netdata/go.d/hdfs.conf
  tags: master

- name: Create netdata stream.conf file
  template: src=netdata/stream.conf.j2 dest=/etc/netdata/stream.conf

- name: Create netdata health.hdfs.conf file
  template: src=netdata/health.hdfs.conf.j2 dest=/etc/netdata/health.d/hdfs.conf

- name: Create netdata health_alarm_notify.conf file
  template: src=netdata/health_alarm_notify.conf.j2 dest=/etc/netdata/health_alarm_notify.conf
