---

- name: Gather facts after connection
  setup:

- name: Wait for cloud-init to finish
  wait_for:
          path: /var/lib/cloud/instance/boot-finished
          state: present
          timeout: 3600
  tags: master

- name: Update apt cache
  apt: update_cache=yes

- name: Create nfs shared data directory
  file:
          state: directory
          path: "{{ home }}/data"
          owner: "{{ user }}"
          group: "{{ group }}"

- name: Include IP addresses
  include_vars:
          file: "../../../terraform/terraform.tfstate.d/{{ lookup('env', 'TF_VAR_cluster_name') }}/outputs.json"
          name: ip_addresses
  tags: master

- name: Write hosts file
  become: yes
  template: src=hosts.j2 dest=/etc/hosts
  tags: master

# NOTE Sanger-specific
- name: Add Sanger domain resolution rule
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    insertafter: "[Resolve]"
    line: "Domains=sanger.ac.uk internal.sanger.ac.uk"

- name: Wait for automatic system updates
  become: true
  shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;
  loop:
    - lock
    - lock-frontend

- name: Install python packages
  become: yes
  apt:
          name: "{{ python_pkgs }}"
          state: latest

- name: Install Java 8 packages
  become: yes
  apt:
          name: "{{ java_pkgs }}"
          state: latest

- name: Install scala
  become: yes
  apt:
          name: scala
          state: latest

- name: Install nfs packages
  become: yes
  apt:
          name: "{{ nfs_pkgs }}"
          state: latest

- name: Disable nfs-server
  service: name=nfs-server state=stopped enabled=no
  tags: master

- name: Install nginx packages
  become: yes
  apt:
          name: "{{ nginx_pkgs }}"
          state: latest
  tags: master

- name: Download nginx sources
  get_url:
    url: "{{ nginx_tarball_url }}"
    dest: "/tmp/{{ nginx_version }}.tar.gz"
  register: nginx_source
  tags: master

- name: Unpack nginx
  unarchive:
    copy: no
    dest: /tmp/
    src: "{{ nginx_source.dest }}"
  when: nginx_source.changed
  register: nginx_source_unpack
  tags: master

- name: Create required Nginx dirs
  become: yes
  file:
          path: "{{ item }}"
          state: directory
          owner: root
          group: root
          mode: 0755
  loop:
          - "{{ nginx_prefix }}"
  tags: master

- name: Install nginx http_substitutions_filter_module
  git:
          repo: https://github.com/yaoweibin/ngx_http_substitutions_filter_module.git
          dest: "{{ subs_filter_path }}"
          version: master
          depth: 1
  when: nginx_source_unpack.changed
  tags: master

- name: Configuring nginx source with custom modules
  become: yes
  command: "./configure --prefix={{ nginx_prefix }} {{ nginx_custom_modules }} --add-module={{ subs_filter_path }}"
  args:
          chdir: "{{ nginx_install_dir }}"
  when: nginx_source_unpack.changed
  register: nginx_configure
  tags: master

- name: Installing nginx
  become: yes
  shell: make && make install
  args:
          chdir: "{{ nginx_install_dir }}"
  when: nginx_configure.changed
  tags: master

- name: Create nginx service file
  become: yes
  template: src=nginx.service.j2 dest=/etc/systemd/system/nginx.service
  tags: master

- name: Install Netdata packages
  become: yes
  apt:
          name: "{{ netdata_pkgs }}"
          state: latest

- name: Download Netdata repo
  git:
          repo: https://github.com/netdata/netdata.git
          dest: "{{ netdata_dir }}"
          version: "{{ netdata_version }}"
          depth: 1

- name: Install extra system packages
  become: yes
  apt:
          name: "{{ extra_pkgs }}"
          state: latest

- name: Start nginx
  service: name=nginx state=started enabled=yes
  tags: master
